#!/bin/sh

export FILEBOT_NODE_HOST="0.0.0.0" # bind to all interfaces

export FILEBOT_CMD="filebot"
export FILEBOT_CMD_CWD="/"
export FILEBOT_CMD_UID=$(id -u)
export FILEBOT_CMD_GID=$(id -g)

export FILEBOT_NODE_DATA="$HOME/.filebot-node"
export FILEBOT_TASK_CMD="/usr/bin/filebot-node-task"

export FILEBOT_NODE_CLIENT="/usr/local/filebot-node/client"

# --optimize_for_size (Enables optimizations which favor memory size over execution speed.)
node --optimize_for_size "/usr/local/filebot-node/server/app.js"
