#!/bin/sh


# silence xpra startup error messages
export XDG_RUNTIME_DIR="/tmp"

mkdir -m 700 -p "/tmp/xpra/0"
mkdir -m 700 -p "/run/user/$PUID/xpra"


# run xpra service
xpra start \
  --start-child="filebot" \
  --exit-with-children \
  --bind-tcp="$XPRA_BIND:$XPRA_PORT" \
  --tcp-auth="$XPRA_AUTH" \
  --daemon=no \
  $XPRA_OPTS 2>&1 \
| grep -v \
  -e 'pointer device emulation using XTest' \
  -e 'uinput' \
  -e "missing 'audio' module" \
  -e 'for Python 3' \
  -e 'failed to choose pdev' \
  -e 'failed to create drisw screen' \
  -e 'some GStreamer elements are missing' \
  -e 'vah264lpenc' \
  -e 'gtk_widget_realize' \
  -e 'encoding failed' \
  -e 'all the codecs have failed' \
  -e '.X11-unix will not be created' \
  -e 'created unix domain socket' \
  -e '/run/user/1000/xpra' \
  -e '/home/ubuntu/.xpra' \
  -e '/tmp/xpra/0/socket' \
  -e 'created abstract sockets' \
  -e '@xpra/0' \
  -e '/data/filebot/.xpra' \
  -e 'private server socket path' \
  -e '/tmp/xpra/0/pulse/pulse/native' \
  -e 'cannot create group socket' \
  -e '/run/dbus/system_bus_socket' \
  -e 'Errno 13' \
  -e 'import asyncore' \
  -e 'watching for applications menu changes' \
  -e '/usr/share/applications' \
  -e '/usr/share/xpra/www' \
  -e '/tmp/xpra/0/server.pid' \
  -e 'ibus-daemon' \
  -e 'D-Bus notification forwarding is available' \
  -e 'start menu entries' \
  -e 'No OpenGL_accelerate module loaded' \
  -e 'xkbcomp' \
  -e 'Could not resolve keysym' \
  -e 'DeprecationWarning' \
  -e '_stop_event' \
  -e 'webcam forwarding is disabled' \
  -e 'video4linux' \
  -e 'v4l2loopback' \
  -e 'webcam' \
  -e 'lpinfo command failed' \
  -e '/usr/sbin/lpinfo' \
  -e 'printer forwarding enabled' \
  -e 'IPv6 loopback address is not supported'
